apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
